version: "2"
run:
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G104
    revive:
      severity: warning
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: unused-parameter
        - name: unnecessary-stmt
        - name: var-naming
        - name: indent-error-flow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - revive
        path: .*\.gen\.go
      - linters:
          - gosec
          - revive
        path: .*_mock\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - your/module/name
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
